#!/usr/bin/env python3
"""Aggregate experiment outputs into standard report bundle."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--input", required=True, help="experiment output dir")
    args = p.parse_args()
    d = Path(args.input)
    d.mkdir(parents=True, exist_ok=True)
    summary = {"status": "skeleton", "dir": str(d)}
    (d / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    (d / "report.md").write_text("# Experiment Report\n\nGenerated by build_report.py skeleton.\n", encoding="utf-8")
    print(f"[report] {d / 'report.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
